import { expect, test } from '@playwright/test'

const PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAoAAAAKACAIAAACDr150AAAHZUlEQVR4nO3VMQEAIAzAMMC/5yFjRxMFfXrnQNfbDoC3M4AAgRkCBBIgMEMAQAKEZggASIDQDAEACRCal4j4OwDAf3EAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCal4g4BgAkQGiGAIAECM0QAJAAoRkCABIgNEMAQAKEZggASIDQDAEACRCa4QBuUgQ64j0LmwAAAABJRU5ErkJggg=='

test('上传图片后展示检测结果', async ({ page }) => {
  await page.goto('/')

  await expect(page.getByTestId('health-status-text')).toContainText(/模型未加载|服务正常/)

  await page.locator('input[type="file"]').setInputFiles({
    name: 'tower.png',
    mimeType: 'image/png',
    buffer: Buffer.from(PNG_BASE64, 'base64')
  })

  await expect(page.getByTestId('image-preview')).toBeVisible()

  await page.getByTestId('analyze-button').click()

  await expect(page.getByTestId('detection-result')).toBeVisible()
  await expect(page.getByText('crack')).toBeVisible()
  await expect(page.getByText('rust')).toBeVisible()
  await expect(page.getByText('deformation')).toBeVisible()
})
